; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
; Pastikan PlatformIO tahu lokasi source dari root folder ini
src_dir = src
include_dir = include
lib_dir = lib
test_dir = test

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
build_flags = -Os

; ===== Upload Settings =====
upload_speed = 460800
upload_flags =
    --before=no_reset
    --after=hard_reset

lib_deps =
    mobizt/Firebase Arduino Client Library for ESP8266 and ESP32 @ ^4.4.14
    madhephaestus/ESP32Servo @ ^3.0.5
    duinowitchery/hd44780 @ ^1.3.2
